---
title: "Visualización del dataset 'tips' con Seaborn"
author: "Rolando Gonzalez"
format:
    html:
        code-fold:true
        theme: cosmo
---


## Visualización de datos en Seaborn


import seaborn as sns
import matplotlib.pyplot as plt

# Cargar el dataset tips
tips = sns.load_dataset("tips")



#| label: fig-boxplot
#| fig-cap: "Distribución de la cuenta total por día de la semana"

plt.figure(figsize=(10, 6))
sns.boxplot(x="day", y="total_bill", data=tips)
plt.title("Distribución de la cuenta total por día de la semana")
plt.show()



#| label: fig-scatterplot
#| fig-cap: "Relación entre cuenta total y propina, por hora del día"

plt.figure(figsize=(10, 6))
sns.scatterplot(x="total_bill", y="tip", hue="time", data=tips)
plt.title("Relación entre cuenta total y propina, por hora del día")
plt.show()



#| label: fig-histogram
#| fig-cap: "Distribución de las propinas"

plt.figure(figsize=(10, 6))
sns.histplot(data=tips, x="tip", kde=True)
plt.title("Distribución de las propinas")
plt.show()

### Reflexión
Profe Nayib
Muchas gracias por que este trabajo me hiso enterder que me falta mucho que aprender.
Que nesesito poner mas atencion en clase que me quiero superar.


Saludos